#!/usr/bin/env bash
# gnostr-proxy sub-shell process
mkdir -p .gnostr
[ ! -d .gnostr/gnostr-proxy ] && cd .gostr &&  git clone --depth 1 --branch master https://github.com/gnostr-org/gnostr-proxy.git
[ -d gnostr-proxy ] && git --assume-unchanged .gnostr && cd gnostr-proxy && make run 2>/dev/null || cd .gnostr/gnostr-proxy && make run 2>/dev/null &
( \
  echo "gnostr-proxy".$$ >/tmp/gnostr-proxy.log; \
# Inside parentheses, and therefore a subshell . . .
while [ 1 ]   # Endless loop.
do
  tail -f /tmp/gnostr-proxy.log; \
  #echo "gnostr-proxy".$$ >/tmp/gnostr-proxy.log; \
    echo $$ | while read line >/tmp/gnostr-proxy.log; \
  do \
    ( \
    echo $line $$ $BASHPID >/tmp/gnostr-proxy.log; \
    ) done; \
  	( \
      echo $$; \
	pnpm install >/dev/null; \
  pnpm run dev >/dev/null; \
)>/tmp/gnostr-proxy.log

done
)&2>/tmp/gnostr-proxy.log
