name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag: [3.13.5]

    container: alpine:${{ matrix.tag }}

    steps:
      ## notice: this is a pre checkout step
      ## notice: additional operations can be done prior to checkout
      - run: apk add nodejs --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --allow-untrusted
      - run: apk add --update nodejs-current

      - run: apk update && apk add file git bash make python3 libtool autoconf automake libtool libc-dev util-linux sed curl
      - uses: actions/checkout@v3
        if: ${{ !env.ACT }}
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'
      ## notice: these are post checkout steps
      - run: make
      - run: make nvm
      - run: make install
      - run: make run
      ## TODO: add ssh config to act sequence
      - run: make tag 2>/dev/null
