name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [11, 10.15]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'

      - run: brew install nvm && nvm install 16 && nvm use 16
      - run: make nvm && source ~/.bashrc && nvm 
