name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [11, 10.15]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'

      - run: printenv
      - run: |
          brew install nvm make && nvm install 16 && nvm use 16 && PATH="/usr/local/opt/make/libexec/gnubin:$PATH" make nvm && source ~/.bashrc && $(which nvm)
